#[build]
#target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/abuteler/.xwin/crt/lib/x86_64",
  "-Lnative=/home/abuteler/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/abuteler/.xwin/sdk/lib/ucrt/x86_64"
]